### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by spfaul** [cryptoAlgorithm/terminal-whatsapp#1]
OS: Windows 10 Build 19042.1165

Unicode chars in the QR Code couldn't print on cmd so I used windows terminal.
Scanning the QR Code immediately crashes the program.

Steps to reproduce:
- clone repo on windows via windows terminal
- npm install
- npm run start
- scan qr code

Monstrous Stacktrace:
```
unexpected error: TypeError: Cannot read property 'toString' of undefined───────────────────────────────────────────────────────────┐
(node:640) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined                                                                │
    at prepareSecretKey (internal/crypto/keys.js:322:11)                                                                            │
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)──────────────────────┐                                         │
    at new Cipheriv (internal/crypto/cipher.js:227:22)can the QR code to login:           │                                         │
    at Object.createCipheriv (crypto.js:123:10)▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄│                                         │
    at Object.aesEncrypt (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:107:24) █   █ █▀▀▀▀▄▀▄█▀▀ ██ ▀▀ █ ██  ▀█▄█ ▀█ █   █ █│                                         │
    at WAConnection.sendBinary (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)█▄▀ █ ▀ ▀ ▀ ▀ █▄█ █▄█ ▀ █ █▄█▄█▄▄▄▄▄▄▄█│                                         │
    at WAConnection.<anonymous> (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)▀ ██ ▀▄█▀▀▀█▄██ ▄ █▀ █ █▀▄ ▀▀█  ▄ ███│                                         │
    at WAConnection.emit (events.js:326:22)█▀  ▀ ▀▄▀▄  ▀█ ██▄▀▄█▄▄ ▄  █ ▀ ▀▄▀▀█▀ ▀█▀█▄▀  █│                                         │
    at WAConnection.emit (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:668:41)▄▄█▄▄ ▄   ▄█▀▄▄▄▄█ █▀███▀▀▀  ▀██ ▀▀█▀█ ██▀█│                                         │
    at WAConnection.connect (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)▄▄  █ █▄▀██▄ █ ▄▄▄ ▄▄▀▀  ▄▀▄██ ▄▄▄ █▀▀██│                                         │
(Use `node --trace-warnings ...` to show where the warning was created)▀█▀█   ▄▄ █▄█ ▀▀▄▀█│                                         │
(node:640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)│              │█▄██▄▄ ▄█ ▄█   ▀▄▀▀▄▀ █▄▀▀▄█▄▀█▄▄ ▀▄▀█▄███▀▀ ▀█│                                         │
(node:640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.▄ ▀▀▄██▄█▄▄▄▄█▄▄▀ ███│                                         │
(node:640) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined  █▀ █ █▀▀   █▄█ █▀ ██│                                         │
    at prepareSecretKey (internal/crypto/keys.js:322:11) ▀▀█▄▄▄█▄▄▄   █▀▀▀  █ █   ▄▄▄ ▀▀██│                                         │
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)▄▄  ▀▀▀█▀▀▄ ▄▀▄██ ▀█▄█│                                         │
    at new Cipheriv (internal/crypto/cipher.js:227:22)███▄█▄█▄▄▄███▄▄█████▄▄████▄█▄▄█▄█▄██│                                         │
    at Object.createCipheriv (crypto.js:123:10)ess Escape, Ctrl + Q or Ctrl + C to quit   │                                         │
    at Object.aesEncrypt (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:107:24)                                                                                        │
    at WAConnection.sendBinary (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)mpose message                                                                    │
    at WAConnection.<anonymous> (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:87:18)
    at WAConnection.emit (events.js:326:22)
    at WAConnection.emit (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:668:41)
    at WAConnection.connect (/mnt/c/Users/Samuel Soo/Downloads/terminal-whatsapp-master/terminal-whatsapp-master/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)
(node:640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by cryptoAlgorithm** [comment]
Related to and closed with same reason as #2
