### ISSUE TITLE
Crashes after QR Code is scanned

### ISSUE THREAD

**Issue by spfaul** [cryptoAlgorithm/terminal-whatsapp#2]
OS: Garuda Linux (Arch)
Kernel: 5.13.9-zen1-1-zen

Steps to reproduce:
- clone repo
- npm install
- npm run start
- scan qr code

Scanning the qr code crashes program and produces the following error:
```
╭─t0a5ted@t0a5ted in repo: terminal-whatsapp on  master [!?] via  v16.9.0 took 36s
╰─λ npm run start

> start
> node ./index.js

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
at new NodeError (node:internal/errors:371:5)
at prepareSecretKey (node:internal/crypto/keys:577:11)
at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
at new Cipheriv (node:internal/crypto/cipher:243:3)
at Object.createCipheriv (node:crypto:138:10)
at Object.aesEncrypt (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:107:24)
at WAConnection.sendBinary (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
at WAConnection.<anonymous> (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
at WAConnection.emit (node:events:406:35)
at WAConnection.emit (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:668:41)
node:internal/errors:464
ErrorCaptureStackTrace(err);
^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
at new NodeError (node:internal/errors:371:5)
at prepareSecretKey (node:internal/crypto/keys:577:11)
at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
at new Cipheriv (node:internal/crypto/cipher:243:3)
at Object.createCipheriv (node:crypto:138:10)
at Object.aesEncrypt (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:107:24)
at WAConnection.sendBinary (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
at WAConnection.<anonymous> (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:87:18)
at WAConnection.emit (node:events:406:35)
at WAConnection.emit (/home/t0a5ted/terminal-whatsapp/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:668:41) {
code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by spfaul** [comment]
unsure if its linked to #1

**Comment by cryptoAlgorithm** [comment]
Ok so it seems like this is an error with Baileys internally. I can't do anything about that, and I suspect you're using the WhatsApp Multidevice beta, which is currently unsupported. Closing this issue.
